FROM docker.elastic.co/beats/filebeat:7.9.2

#COPY config/. /usr/share/filebeat/
#USER root
#RUN chown root:filebeat /usr/share/filebeat/filebeat.yml


# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
